apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-endpoints
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "configmaps"]
    verbs: ["get", "list", "watch"]
