apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu
  labels:
    app: cpu
spec:
  selector:
    matchLabels:
      app: cpu
  replicas: 1
  template:
    metadata:
      name: cpu
      labels:
        app: cpu
    spec:
      containers:
        - name: cpu
          imagePullPolicy: Always
          image: drakus73/micro:cpu
          ports:
            - containerPort: 8090
              name: cpu-port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
