apiVersion: apps/v1
kind: Deployment
metadata:
  name: disc
  labels:
    app: disc
spec:
  selector:
    matchLabels:
      app: disc
  replicas: 1
  template:
    metadata:
      name: disc
      labels:
        app: disc
    spec:
      containers:
        - name: disc
          imagePullPolicy: Always
          image: drakus73/micro:disc
          ports:
            - containerPort: 8091
              name: disc-port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
