apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk
  labels:
    app: disk
spec:
  selector:
    matchLabels:
      app: disk
  replicas: 1
  template:
    metadata:
      name: disk
      labels:
        app: disk
    spec:
      containers:
        - name: disk
          imagePullPolicy: Always
          image: drakus73/micro:disk
          ports:
            - containerPort: 8091
              name: disk-port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
