apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu
  labels:
    app: gpu
spec:
  selector:
    matchLabels:
      app: gpu
  replicas: 1
  template:
    metadata:
      name: gpu
      labels:
        app: gpu
    spec:
      containers:
        - name: gpu
          imagePullPolicy: Always
          image: drakus73/micro:gpu
          ports:
            - containerPort: 8092
              name: gpu-port
