apiVersion: apps/v1
kind: Deployment
metadata:
  name: motherboard
  labels:
    app: motherboard
spec:
  selector:
    matchLabels:
      app: motherboard
  replicas: 1
  template:
    metadata:
      name: motherboard
      labels:
        app: motherboard
    spec:
      containers:
        - name: motherboard
          imagePullPolicy: Always
          image: drakus73/micro:motherboard
          ports:
            - containerPort: 8093
              name: motherboard-port
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
