apiVersion: v1
kind: Service
metadata:
  name: central
  labels:
    app: central
spec:
  type: ClusterIP
  selector:
    app: central
  ports:
    - port: 7092
      protocol: TCP
      targetPort: 7092
