apiVersion: v1
kind: Service
metadata:
  name: ip-service
  labels:
    app: ip-service
spec:
  type: ClusterIP
  selector:
    app: ip-service
  ports:
    - port: 7090
      protocol: TCP
      targetPort: 7090
