apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  annotations:
    loadbalancer.openstack.org/x-forward-for: "true"
spec:
  type: LoadBalancer
  selector:
    app: central
  ports:
    - name: http
      port: 80
      targetPort: 7092
